baseurl = "https://markkurzeja.github.io"
DefaultContentLanguage = "en"
title = "TensorTales"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  author.name = "Mark Kurzeja"
  homeTitle = "TensorTales Blog" # Set a different text for the header on the home page
  subtitle = "A research blog with other random thoughts"
  mainSections = ["post","posts"]
  logo = "logo/logo_close.png" # Expecting square dimensions
  favicon = "logo/logo.ico"
  dateFormat = "Jan 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

# [[Params.bigimg]]
#   src = "banner/banner.png"
  # desc = "Triangle"
# [[Params.bigimg]]
#   src = "img/triangle.jpg"
#   desc = "Triangle"
# [[Params.bigimg]]
#   src = "img/sphere.jpg"
#   desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
# [[Params.bigimg]]
#   src = "img/hexagon.jpg"
#   desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Mark Kurzeja"
  # website = "yourwebsite.com"
  # email = "youremail@domain.com"
  # facebook = "username"
  github = "MarkKurzeja"
  # gitlab = "username"
  # bitbucket = "username"
  # twitter = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"
  # medium = "username"
  # discord = "invite code (https://discord.gg/XXXXXXX)"
  # strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
